---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

  network:
    - ["private_network", {ip: "33.33.33.33"}]

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.5.0

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[demo_users::default]
    attributes:
